### ISSUE TITLE
Missing file Application.h  when testing smooth

### ISSUE THREAD

**Issue by icodk** [PerMalmberg/Smooth-test#1]
CXX build/main/main.o
In file included from C:/msys32/home/ico/esp/projects/Smooth-test/main/main.cpp:6:0:
C:/msys32/home/ico/esp/projects/Smooth-test/main/test/test_rgb_led.h:5:37: fatal error: smooth/core/Application.h: No such file or directory
compilation terminated.
make[1]: *** [/home/ico/esp/esp-idf/make/component_wrapper.mk:286: main.o] Error 1
make: *** [C:/msys32/home/ico/esp/esp-idf/make/project.mk:468: component-main-build] Error 2
make: *** Waiting for unfinished jobs....

**Comment by PerMalmberg** [comment]
That file is part of Smooth, you’ve not retrieved all files. git submodule update?
