### ISSUE TITLE
Large MQTT message

### ISSUE THREAD

**Issue by Romkabouter** [PerMalmberg/Smooth-test#3]
Hi there, I have a esp32 chip and my current software is running into some limits.
This is regarding the receiving buffer size of a MQTT message.
Currently, in your software a valid range is update 4096, but I need much more than that.
The message contains wav files, but should not be larger than 1 MB
Is your framework capable of receiving such large messages?

I do not have influence on the receiving messages, this is from another software source

**Comment by PerMalmberg** [comment]
You can configure the maximum size of a MQTT message in ‘make menuconfig’ at the expense of increased memory usage. However, the ESP32 only have a total of 520kb memory so 1MB is way over the practical limit, at least unless you buffer data to flash. Even then, 1MB is a lot of data for this kind of device. (This is the reason the the current implementation silently acknowledge but throws away messages that are larger than the configured limit)

Regarding buffering to flash, Smooth can only do in-memory operations, but feel free to propose a persistence layer for the MQTT parts of the framework via a PR. 

I’m glad to hear someone else finding this useful, may I ask what you are building and if for private/commercial use?

**Comment by PerMalmberg** [comment]
Also, any feedback on Smooth in general is welcome!

**Comment by PerMalmberg** [comment]
Oh, I remember now - 4096 is the maximum configurable size. That is an arbitrary number I chose. It can be increased as long as you have memory available. The framework itself has no (known) restrictions regarding the size.

**Comment by Romkabouter** [comment]
You can check my project here: https://github.com/Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer

I am not an advanced c++ programmer, so it all might seem a bit sloppy.
The purpose is to implement an Snips Audio Server. It almost works correctly, but Snips sends a wav file to a playBytes topic, which is the audio to be played send as buffer.
The biggest is over 95000 bytes, so it gets swallowed by the mqtt library.

I was wondering if you framework somehow could work with this, but the memory is an issue indeed.
I saw the 4096 in de Kconfig and can be easily adjusted, so I think I can give it a shot somehow :)

**Comment by PerMalmberg** [comment]
You'd probably best add a flash buffer as you can't hold it all in memory. Or, use another module with more  RAM.

**Comment by Romkabouter** [comment]
I can't use another module, because it is build in the device: https://matrix-io.github.io/matrix-documentation/matrix-voice/overview/

Flash buffer... if only I knew how.... I am quite the nood in esp32

**Comment by PerMalmberg** [comment]
Flash buffer isn't really ESP32-specific (except the the parts needed to set up the filesystem). I haven't looked that the schematics, but could you add a SD-card to that device? If so, you could use that as a storage.

**Comment by Romkabouter** [comment]
No SD card, I am trying to figure our your framework :)

**Comment by PerMalmberg** [comment]
Let me know if you find anything funny :) I'll close this thread as the original question has been answered.
